# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='event_pic')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
