# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventHandler', '0011_event_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_pic')),
                ('remark', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='eventimage', to='EventHandler.Event')),
            ],
        ),
    ]
