# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='remark',
        ),
    ]
