# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventHandler', '0011_event_review'),
        ('FileUpload', '0003_auto_20180317_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='event',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='eventimage', to='EventHandler.Event'),
        ),
    ]
