# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0004_eventimage_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventimage', to='EventHandler.Event'),
        ),
    ]
