# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0007_eventimage_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='event',
        ),
    ]
