# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrizeHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to=settings.AUTH_USER_MODEL),
        ),
    ]
