# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.SmallIntegerField(choices=[(3, 'ENDED'), (2, 'ONGOING'), (1, 'INCOMING')], default=1),
        ),
    ]
