# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 16:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventHandler', '0011_event_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(default=True)),
                ('session', models.CharField(max_length=200)),
                ('votes', models.IntegerField()),
                ('views', models.IntegerField()),
                ('event', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='livestreams', to='EventHandler.Event')),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='livestreams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_voted', models.BooleanField(default=False)),
                ('livestream', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='OpenTokHandler.Livestream')),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
