# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OpenTokHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('status', models.SmallIntegerField(choices=[(2, 'APPROVED'), (1, 'PENDING'), (3, 'REJECTED')], default=1)),
                ('sentby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sentby', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='archive',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='archive_pic'),
        ),
    ]
