# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTokHandler', '0003_auto_20180325_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestreams', to='event.Event'),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestreams', to=settings.AUTH_USER_MODEL),
        ),
    ]
