# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTokHandler', '0004_reporttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='message',
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='OpenTokHandler.ReportType'),
        ),
    ]
