# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTokHandler', '0004_livestream_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewer',
            old_name='has_voted',
            new_name='vote',
        ),
        migrations.AlterField(
            model_name='livestream',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
