# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTokHandler', '0005_auto_20180330_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
