# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_video'),
        ('OpenTokHandler', '0005_auto_20180326_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.CharField(blank=True, default='', max_length=200)),
                ('livestream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='OpenTokHandler.Livestream')),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='file_upload.Video')),
            ],
        ),
    ]
