# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTokHandler', '0006_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='video',
            field=models.URLField(blank=True, default=''),
        ),
    ]
