# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTokHandler', '0006_viewer_is_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='is_moderator',
        ),
    ]
