# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTokHandler', '0008_archive_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
