# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180330_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_code',
            field=models.IntegerField(default=4103, max_length=9999),
        ),
    ]
