# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 07:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(max_length=4, null='', validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
