# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20180330_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_uuid',
        ),
    ]
