# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='video')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
