# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTokHandler', '0007_auto_20180326_1601'),
        ('file_upload', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
