# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 02:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EventHandler', '0002_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 3, 2, 33, 20, 232950, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 2, 33, 20, 232950, tzinfo=utc)),
        ),
    ]
