# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_business_user'),
        ('EventHandler', '0004_auto_20180302_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='UserProfile.Business'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 3, 16, 26, 16, 433118, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 16, 26, 16, 433118, tzinfo=utc)),
        ),
    ]
