# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHandler', '0006_auto_20180302_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='/static/images'),
        ),
    ]
