# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHandler', '0010_auto_20180303_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='review',
            field=models.IntegerField(choices=[(2, 'Approved'), (1, 'Pending'), (3, 'Rejected')], default=1),
        ),
    ]
