# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventHandler', '0011_event_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
