# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHandler', '0012_remove_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='review',
            field=models.SmallIntegerField(choices=[(2, 'Approved'), (1, 'Pending'), (3, 'Rejected')], default=1),
        ),
    ]
