# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0008_remove_eventimage_event'),
        ('EventHandler', '0013_auto_20180318_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventimage', to='FileUpload.EventImage'),
        ),
    ]
