# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventHandler', '0014_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='company',
            new_name='business',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='FileUpload.EventImage'),
        ),
    ]
